# Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: CC0-1.0

name: Build

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: pyproject.toml
          python-version: "3.10"
      - name: Upgrade pip
        run: python -m pip install -U pip
      - name: Install pre-commit
        run: python -m pip install pre-commit types-docutils
      - name: Run Pre-Commit
        run: pre-commit run --all-files
