# Copyright DB Netz AG and contributors
# SPDX-License-Identifier: CC0-1.0

name: Build

on:
  push:
    branches: ["*"]
    tags: ["v*.*.*"]

jobs:
  test:
    name: Test with Python ${{matrix.python_version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - os: windows-latest
            python_version: "3.10"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python_version}}
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: pyproject.toml
          python-version: ${{matrix.python_version}}
      - name: Upgrade Pip
        run: python -m pip install -U pip
      - name: Install test dependencies
        run: python -m pip install '.[test]'
      - name: Run unit tests
        run: python -m pytest --cov-report=term --cov=capella_git_hooks --rootdir=.
