# Copyright DB Netz AG and contributors
# SPDX-License-Identifier: CC0-1.0

name: Docs

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sphinx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          python -m pip install -U pip
      - name: Install dependencies
        run: |
          python -m pip install '.[docs]'
      - name: Auto-generate APIDOC sources
        run: |-
          sphinx-apidoc --output-dir docs/source/code --force .
      - name: Create docs
        run: |
          make -C docs html
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
